### ISSUE TITLE
654: failed assertion `Function writes texture (outTexture[0]) whos usage (0x05) doesn't specify MTLTextureUsageShaderWrite (0x02)'

### ISSUE THREAD

**Issue by bryan1anderson** [FlexMonkey/ParticleLab#29]
get this error:

654: failed assertion `Function writes texture (outTexture[0]) whos usage (0x05) doesn't specify MTLTextureUsageShaderWrite (0x02)'

at this line of code:
        commandEncoder.dispatchThreadgroups(threadgroupsPerGrid, threadsPerThreadgroup: threadsPerThreadgroup)

**Comment by FlexMonkey** [comment]
Hi,

This appears to be a bug in the latest GA releases of Xcode 7 and/or iOS. I've raised a Radar, in the meantime, the fix is to turn off Metal API validation under Product -> Scheme -> Options and everything should work perfectly.

There was an identical bug in OS X 10.11.1 which is fixed in 10.11.2, so I'm quietly confident that it will be fixed in the next release of iOS.

Cheers,

Simon
